version: '3.9'
services:
  admin_backend:
    build: .
    ports:
      - "8004:8000"
    volumes:
      - .:/app
    depends_on:
      - admin_db
    command: 'php artisan serve --host=0.0.0.0'
    networks:
      - admin
      - kafka
      - users

  admin_queue:
    build: .
    depends_on:
      - admin_db
    volumes:
      - .:/app
    command: 'php artisan queue:work'
    networks:
      - admin
      - kafka

  admin_db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: admin
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - "33065:3306"
    networks:
      - admin

networks:
  admin:
  kafka:
    name: kafka
    external: true
  users:
    name: users
    external: true
