version: '3.9'
services:
  admin_backend:
    build: .
    ports:
      - "8004:8000"
    volumes:
      - .:/app
    depends_on:
      - admin_db
    command: 'php artisan serve --host=0.0.0.0'
    networks:
      - admin
      - proxynet
      - users

#  admin_queue:
#    build: .
#    depends_on:
#      - admin_db
#    command: 'php artisan queue:work'
#    networks:
#      - admin
#      - proxynet

  admin_db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: admin
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - "33070:3306"
    networks:
      - admin

networks:
  proxynet:
    name: pub_sub_network
    external: true
  admin:
  users:
    name: users
    external: true
