version: '3.9'
services:
  backend:
    build: .
    container_name: laravel-ambassador-backend
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db
    command: 'php artisan serve --host=0.0.0.0'
    networks:
      - proxynet

  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: ambassador
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - 33066:3306
    networks:
      - proxynet

  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - proxynet

  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui
    networks:
      - proxynet

  zookeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2185:2181"
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
    volumes:
      - "./storage/zookeeper/data:/var/lib/zookeeper/data"
      - "./storage/zookeeper/log:/var/lib/zookeeper/log"
      - "./storage/zookeeper/secrets:/var/lib/zookeeper/secrets"
    networks:
      - proxynet

  kafka:
    image: confluentinc/cp-kafka:latest
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    depends_on:
      - zookeper
    volumes:
      - "./storage/kafka/data:/var/lib/kafka/data"
      - "./storage/kafka/secrets:/var/lib/kafka/secrets"
    networks:
      - proxynet

  kafdrop:
    image: obsidiandynamics/kafdrop
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:9092"
    depends_on:
      - kafka
    networks:
      - proxynet

networks:
  proxynet:
    name: pub_sub_network
    external: true
