version: '3.7'
services:
  ambassador_backend:
    build: .
    ports:
      - "8003:8000"
    volumes:
      - .:/app
    depends_on:
      - ambassador_db
    command: 'php artisan serve --host=0.0.0.0'
    networks:
      - kafka
      - ambassador
      - users

  ambassador_db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: ambassador
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - 33069:3306
    networks:
      - ambassador

  ambassador_queue:
    build: .
    depends_on:
      - ambassador_db
    volumes:
      - .:/app
    environment:
      CACHE_DRIVER: file
    command: 'php artisan queue:work'
    networks:
      - ambassador
      - kafka

  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - ambassador

networks:
  kafka:
    name: kafka
    external: true
  users:
    name: users
    external: true
  ambassador:
