version: '3.9'
services:
  email_backend:
    build: .
    ports:
      - "8001:8000"
    volumes:
      - .:/app
    command: 'php artisan queue:work'
    networks:
      - kafka

networks:
  kafka:
    name: kafka
    external: true
