version: '3.7'
services:
  email_backend:
    build: .
    container_name: microservice-emails
    ports:
      - 8001:8000
    volumes:
      - .:/app
    command: 'php artisan queue:work'
    networks:
      - kafka

networks:
  kafka:
    name: kafka
    external: true
