version: '3.7'
services:
  backend:
    build: .
    container_name: microservice-emails
    ports:
      - 8001:8000
    volumes:
      - .:/app
    command: 'php artisan serve --host=0.0.0.0'
    networks:
      - proxynet

networks:
  proxynet:
    name: pub_sub_network
    external: true
