version: '3.9'
services:
  checkout_backend:
    build: .
    ports:
      - "8002:8000"
    volumes:
      - .:/app
    depends_on:
      - checkout_db
    command: 'php artisan serve --host=0.0.0.0'
    networks:
      - checkout
      - proxynet
      - users

  checkout_db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: checkout
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - "33068:3306"
    networks:
      - checkout

networks:
  proxynet:
    name: pub_sub_network
    external: true
  checkout:
  users:
    name: users
    external: true
