version: '3.9'
services:
  checkout_backend:
    build: .
    ports:
      - "8002:8000"
    volumes:
      - .:/app
    depends_on:
      - checkout_db
    command: 'php artisan serve --host=0.0.0.0'
    networks:
      - checkout
      - kafka
      - users

  checkout_queue:
    build: .
    depends_on:
      - checkout_db
    volumes:
      - .:/app
    command: 'php artisan queue:work'
    networks:
      - checkout
      - kafka

  checkout_db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: checkout
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - "33067:3306"
    networks:
      - checkout

networks:
  checkout:
  kafka:
    name: kafka
    external: true
  users:
    name: users
    external: true
