version: '3.9'
services:
  users_backend:
    build: .
    container_name: users_ms
    volumes:
      - .:/app
    depends_on:
      - users_db
    command: 'php artisan serve --host=0.0.0.0'
    networks:
      - users

  users_db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: users
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    ports:
      - "33067:3306"
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    networks:
      - users

networks:
  users:
    name: users
